#create channel as #test_YYYYMMDD-HHmm
#c.f. https://get.slack.help/hc/en-us/articles/201402297-Create-a-channel
channel_name_prefix: test

tasks:
  - task1
  - task2
  - task3

members:
  - user1
  - user2
  - user3
